### ISSUE TITLE
Basic crash

### ISSUE THREAD

**Issue by Jino42** [Krystalz42/nibbler#11]
1 S
1 C
1 E
1 R
2 C
2 E
2 R
1 X

Attendre la mort

1X

    ==30693==The signal is caused by a READ memory access.
    ==30693==Hint: address points to the zero page.
    #0 0x10a2d3214 in KINU::World::createEntity() World.cpp:40
    #1 0x10a1b4072 in Factory::createSnake(Snake const&, int) Factory.cpp:42
    #2 0x10a1b38c1 in Factory::createAllSnake(std::__1::array<Snake, 8ul>&, short) Factory.cpp:25
    #3 0x10a28320a in SnakeClient::callbackStartInfo(StartInfo) SnakeClient.cpp:274

**Comment by Jino42** [comment]
Sa arrive pas tout le temps !
Mais si on spam X a chaque fin de game, pour la relance, sa devrait arriver courrament

**Comment by Krystalz42** [comment]
Still working
