### ISSUE TITLE
SnakeArray wrong when ClientDisconnect

### ISSUE THREAD

**Issue by Jino42** [Krystalz42/nibbler#12]
1SCE
2CE
3CE
2D
3D

3 reste visible dans le lobby
Parfois sa entraine des Pb plus gros, genre, quand un client exit, sa fait leave qqun d'autre dans le lobby (Uniquement sur la Gui)

**Comment by Jino42** [comment]
`SnakeServer::callbackDeadConnection(size_t index)`

Ce qu’on obtient c’est l’index de la connections (Soit juste sa place dans le tableau de connection du serv)
Mais pas indexConnections qui est dans stocké dans `Snake` (Normal)

Mai du coup
Si on déco le 2, puis le 3
Le 3 est a l’index 1 du tableau de connections
Et ensuite, aucun snake n’a de indexConnection a  1

**Comment by Krystalz42** [comment]
2ez
