### ISSUE TITLE
SEGV

### ISSUE THREAD

**Issue by alexandre-roulin** [Krystalz42/nibbler#17]
==26556==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x00010c754512 bp 0x7ffeef21ef70 sp 0x7ffeef21eda0 T0)
==26556==The signal is caused by a READ memory access.
==26556==Hint: address points to the zero page.
    #0 0x10c754511 in std::__1::__deque_base<Mesh, std::__1::allocator<Mesh> >::begin() const __split_buffer:82
    #1 0x10c6fa5a7 in Model::render(Shader&, unsigned int) const deque:1274
    #2 0x10c68b151 in ActModel::render(Shader&, unsigned int) ActModel.cpp:31
    #3 0x10c6ace74 in DisplayGlfw::drawGridCase_(eSprite, int, int) DisplayGlfw.cpp:235
    #4 0x10c6ae133 in DisplayGlfw::drawGrid(MutantGrid<eSprite> const&) DisplayGlfw.cpp:272
    #5 0x100b2a1df in Univers::updateDisplayUI() Univers.cpp:546
    #6 0x100e0539d in GameManager::loopUI() GameManager.cpp:170
    #7 0x100b13444 in Univers::startNewGame() Univers.cpp:128
    #8 0x1009e80bd in nibbler(Univers&) main.cpp:17
    #9 0x1009eceb8 in main main.cpp:103
    #10 0x7fff6b7cfed8 in start (libdyld.dylib:x86_64+0x16ed8)

**Comment by Krystalz42** [comment]
Je sais plus comment je l'ai fais

**Comment by Krystalz42** [comment]
C'etait au lancement de la game en tout cas
