### ISSUE TITLE
2 Server on same Adress

### ISSUE THREAD

**Issue by Jino42** [Krystalz42/nibbler#3]
1 S
2 S

libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::system::system_error> >: bind: Address already in use

[nibbler[4664].pdf](https://github.com/Krystalz42/nibbler/files/2894200/nibbler.4664.pdf)

**Comment by Krystalz42** [comment]
j'ai ecris du bullshit :'(

**Comment by Krystalz42** [comment]
J'ai pas ecris du bullshit because ca work
